version: 4
shared:
  image: markinva/visibility-screwdriver-7:latest
  environment:
    ANSIBLE_VAULT_PASSWORD_FILE: sd_vault
    ANSIBLE_HOST_KEY_CHECKING: false
  secrets:
    - VAULT_KEY
    
jobs:
    main:
        requires: []
        steps:
            - echo "Woot"

    visibility:
        steps:
            - echo hi

    visibility-moloch:
        steps:
            - echo hi

    visibility-moloch2:
        requires: ["visibility-moloch"]
        steps:
            - echo hi

    visibility-moloch3:
        requires: ["visibility-moloch2"]
        steps:
            - echo hi

    visibility-bro:
        steps:
            - echo hi

    visibility-bro2:
        requires: ["visibility-bro"]
        steps:
            - echo hi

    visibility-bro3:
        requires: ["visibility-bro"]
        steps:
            - echo hi

    visibility-suricata1:
        steps:
            - echo hi

    visibility-suricata2:
        steps:
            - echo hi

    visibility-suricata3:
        requires: ["visibility-suricata1", "visibility-suricata2"]
        steps:
            - echo hi

    visibility-moloch-install:
        requires: ["visibility-suricata1", "visibility-suricata2", "visibility-suricata3"]
        steps:
            - echo hi

    visibility-moloch-install222222222222222222222inst:
        requires: ["visibility-moloch-install"]
        steps:
            - echo hi
    visibility-moloch-install222222222222222222222ins2:
        requires: ["visibility-moloch-install222222222222222222222inst"]
        steps:
            - echo hi
    visibility-moloch-install222222222222222222222ins3:
        requires: ["visibility-moloch-install222222222222222222222ins2"]
        steps:
            - echo hi
            
    visibility-moloch-restart:
        steps:
            - echo hi

    visibility-moloch-stop:
        steps:
            - echo hi

    visibility-moloch-start:
        steps:
            - echo hi

    visibility-moloch-cert:
        steps:
            - echo hi

    moloch-viewer:
        steps:
            - echo hi

    moloches:
        steps:
            - echo hi

    moloches-iptables:
        steps:
            - echo hi

    moloch-wise:
        steps:
            - echo hi

    visibility-os-upgrade:
        steps:
            - echo hi

    visibility-disk-check:
        steps:
            - echo hi

    moloches-os-upgrade:
        steps:
            - echo hi

    moloches-disk-check:
        steps:
            - echo hi
            - echo hi

    disk-check:
        steps:
            - echo hi
